
services:
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: historical-events-db
    environment:
      POSTGRES_DB: historical_events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: historical-events-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: historical_events
      DB_SSL_MODE: disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: historical-events-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: migrator
    container_name: historical-events-migrate
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/historical_events?sslmode=disable
    profiles:
      - tools
