// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logo/Cartographic.tsx": () => import("../components/mockups/logo/Cartographic.tsx"),
  "./components/mockups/logo/Diver.tsx": () => import("../components/mockups/logo/Diver.tsx"),
  "./components/mockups/logo/GlobeClock.tsx": () => import("../components/mockups/logo/GlobeClock.tsx"),
  "./components/mockups/logo/GlobeClockDark.tsx": () => import("../components/mockups/logo/GlobeClockDark.tsx"),
  "./components/mockups/logo/GlobeClockRadial.tsx": () => import("../components/mockups/logo/GlobeClockRadial.tsx"),
  "./components/mockups/logo/GlobeClockSepia.tsx": () => import("../components/mockups/logo/GlobeClockSepia.tsx"),
  "./components/mockups/logo/Hourglass.tsx": () => import("../components/mockups/logo/Hourglass.tsx")
};
