// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logo/Cartographic.tsx": () => import("../components/mockups/logo/Cartographic.tsx"),
  "./components/mockups/logo/Diver.tsx": () => import("../components/mockups/logo/Diver.tsx"),
  "./components/mockups/logo/Hourglass.tsx": () => import("../components/mockups/logo/Hourglass.tsx")
};
